### ISSUE TITLE
DNS not resolved

### ISSUE THREAD

**Issue by spiderpug** [jfrazelle/onion#3]
Hi, 

thanks for this project. Actually this was exactly what I was looking for!

I tried to follow the docs and started everything without noticeable errors but my app containers cannot resolve DNS it seems:

```
@da5e3bcb90a0:~> curl canihazip.com/s
curl: (6) Couldn't resolve host 'canihazip.com'
```

Is there any meaningful way to provide debug information?

**Comment by jessfraz** [comment]
Ya I think it stopped working after docker version 1.9 I don’t really
support it anymore

**Comment by jessfraz** [comment]
closing as i am going to archive this
